export const COMMON_HANDLE_SEARCH_BEGIN = 'COMMON_HANDLE_SEARCH_BEGIN';
export const COMMON_HANDLE_SEARCH_SUCCESS = 'COMMON_HANDLE_SEARCH_SUCCESS';
export const COMMON_HANDLE_SEARCH_FAILURE = 'COMMON_HANDLE_SEARCH_FAILURE';
export const COMMON_HANDLE_SEARCH_DISMISS_ERROR = 'COMMON_HANDLE_SEARCH_DISMISS_ERROR';
