export const VIEWS_ADD_TO_CART = 'VIEWS_ADD_TO_CART';
export const VIEWS_REMOVE_FROM_CART = 'VIEWS_REMOVE_FROM_CART';
export const VIEWS_UPDATE_ITEM_COUNT = 'VIEWS_UPDATE_ITEM_COUNT';
export const VIEWS_UPDATE_CART_TOTAL='VIEWS_UPDATE_CART_TOTAL';
